name: Docker ECR Push

on:
  push:
    branches: [main]
    tags:
      - v**
      - '*/v**'
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  docker-ecr-push:
    strategy:
      matrix:
        include:
          - binary: signet
            dockerfile: Dockerfile
          - binary: signet-exex
            dockerfile: Dockerfile.exex
          - binary: signet-sidecar
            dockerfile: Dockerfile.sidecar
    uses: init4tech/actions/.github/workflows/ecr-build-and-push.yml@main
    with:
      rust-binary-name: ${{ matrix.binary }}
      dockerfile-path: ${{ matrix.dockerfile }}
      environment: dev
    secrets:
      aws-ecr-repository: ${{ secrets.AWS_ECR_REPOSITORY }}
      aws-ecr-deployer-role-arn: ${{ secrets.AWS_ECR_DEPLOYER_ROLE_ARN }}
